### ISSUE TITLE
EU - Google Contest page blocking

### ISSUE THREAD

**Issue by etrock** [dine-5h/gnews-scraper#1]
In the EU the scraper returns with an empty array, because Google redirects you to their contest site because of GDPR:

[https://consent.google.com/m?continue=https://news.google.com/search?q%3DProptech%2Bwhen:7h%26hl%3Den-US%26gl%3DUS%26ceid%3DUS:en&gl=HU&m=0&pc=n&cm=2&hl=en-US&src=1](https://consent.google.com/m?continue=https://news.google.com/search?q%3DProptech%2Bwhen:7h%26hl%3Den-US%26gl%3DUS%26ceid%3DUS:en&gl=HU&m=0&pc=n&cm=2&hl=en-US&src=1)

**Comment by dstark5** [comment]
the issue will be fixed in couple of days

**Comment by dstark5** [comment]
EU consent screen issue has been fixed in new version 1.2.1
